name: DDANet
target_size: &target_size !!python/tuple [128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/fast_mri/sota/
#
# Experiment
#
experiment:
  name: DDANet
  task: train
  weights: # ''
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.DDANet
  class_name: DDANet
  params:
    cdim: 1
    zdim: 128
    channels:
      - 64
      - 128
      - 256
      - 512
      - 512
    image_size: 128
    conditional: False
#
# Trainer
#
trainer:
  module_name: projects.25_DDANet.DDANet_Trainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 1500
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    # Optimizer
    patience: 500
    optimizer_params:
      lr: 5.0e-5 # 2.0e-4 $ orig
  # Data Loader
  data_loader:
# IXI-T1
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.fastmri_loader
          class_name: FastLoader
        data_dir:
          train:
          - './data/SC2CT/train.csv'
          val:
          - './data/SC2CT/val.csv'
          test:
          - './data/SC2CT/train_test.csv'
        target_size: *target_size
        batch_size: 16

downstream_tasks:
  detection:
    module_name: projects.25_DDANet.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    global_detection: True
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          target_size: *target_size
          batch_size: *dbatch_size
          dataset_module:
            module_name: data.loaders.fastmri_loader
            class_name: FastLoader
      datasets:
        test_Normal:
          data_dir:
            test:
              - './data/SC2CT/test_normal.csv'
        test_abnormal:
          data_dir:
            test:
              - './data/SC2CT/test_abnormal.csv'
